language: java
jdk: oraclejdk8
before_install:
 - chmod +x gradlew
notifications:
 irc:
  channels:
   - "irc.esper.net#batman"
  template:
   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
   - "Build details : %{build_url} | %{result}%"